services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tinybin
    networks:
      - pastefox-network
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 10

  pastefox:
    image: ghcr.io/foxyiscoding/pastefox:latest
    environment:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      WEB_PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - pastefox-network
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:

networks:
  pastefox-network:
    driver: bridge