version: '3.8'

services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pastefox
      MYSQL_USER: pastefox
      MYSQL_PASSWORD: pastefox
    networks:
      - pastefox-network
    volumes:
      - db-data:/var/lib/mysql

  pastefox:
    image: ghcr.io/loudbooks/pastefox:latest
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: pastefox
      DB_PASSWORD: pastefox
      DB_NAME: pastefox
      WEB_PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - pastefox-network
    depends_on:
      - db

volumes:
  db-data:

networks:
  pastefox-network:
    driver: bridge