version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tinybin
    networks:
      - tinybin-network
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  tinybin:
    image: ghcr.io/foxyiscoding/tinybin:latest
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tinybin
      WEB_PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
      - "5173:5173"
    networks:
      - tinybin-network
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  db-data:
    name: tinybin-db-data

networks:
  tinybin-network:
    name: tinybin-network
    driver: bridge