name: Build and Publish Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Commit Hash
        id: get_commit_hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set Docker Tags
        id: set_tags
        run: |
          echo "tag=latest" >> $GITHUB_ENV

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-pastefox
          key: ${{ runner.os }}-pastefox-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pastefox-buildx-

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            COMMIT_HASH=${{ env.hash }}
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=local,src=/tmp/.buildx-cache-pastefox
          cache-to: type=local,dest=/tmp/.buildx-cache-pastefox-new,mode=max
          tags: |
            ghcr.io/foxyiscoding/pastefox:${{ env.tag }}
            ghcr.io/foxyiscoding/pastefox:${{ env.hash }}

      - name: Move updated Docker cache
        run: |
          rm -rf /tmp/.buildx-cache-pastefox
          mv /tmp/.buildx-cache-pastefox-new /tmp/.buildx-cache-pastefox
